### ISSUE TITLE
White text on white backgound in context menus

### ISSUE THREAD

**Issue by Virkkunen** [coekuss/quietfox#1]
Using Quietfox for Firefox 70+, I'm facing a issue where the context menu (right click) background and text are white. My theme is dark and I also commented the section to make the menus color adaptable (lines 49-56), to no avail. Issue only happens on this theme.

![firefox_2019-11-09_12-01-55](https://user-images.githubusercontent.com/9111925/68530674-3bac3b00-02e9-11ea-98cf-64461bb022ae.png)

While taking this screenshot I also noticed there's a square to the upper right part of each tab that overlaps whatever is there.

**Comment by coekuss** [comment]
This may have been happening because I forgot to push my updated version of this mod to the actual Github repository, I just had the file download link lower on the readme page. I've fixed this now, you can try re-downloading.

**Comment by icejr** [comment]
I'm using Firefox 72.0 and can confirm this it's still present

**Comment by coekuss** [comment]
I realized this was previously a difference in Nightly vs Stable, but now it seems both Stable and Nightly have the issue, so I'll be releasing a new Quietfox soon. I've only been developing Quietfox for Firefox Stable because Nightly is subject to change more often and would require more frequent updates and maintenance from me

**Comment by coekuss** [comment]
Just released the new update for Firefox 71, try redownloading now and let me know if everything is good
